### ISSUE TITLE
No tools.feature module.

### ISSUE THREAD

**Issue by bharathichezhiyan** [bpopeters/mg2p#1]
python mg2p.py spanish-model -preprocess
Traceback (most recent call last):
  File "mg2p.py", line 3, in <module>
    from tools.model import G2PModel
  File "/home/miharc/bharaj/mg2p/tools/model.py", line 9, in <module>
    from tools.features import G2PRule, AvgG2PFeature
ImportError: No module named 'tools.features'

**Comment by bharathichezhiyan** [comment]
Please give the full command with an example for executing the program.

**Comment by bpopeters** [comment]
Whoops, I forgot to add some of my files.
